export const theme = {
  colors: {
    primary: '#1A6B5A',
    primaryLight: '#E8F5F1',
    primaryDark: '#0F4D40',
    background: '#F8F7F4',
    surface: '#FFFFFF',
    textPrimary: '#1C2B26',
    textSecondary: '#4A7A6A',
    textTertiary: '#888780',
    border: '#E8E5DF',
    danger: '#D94F3D',
    dangerLight: '#FFE8E6',
    warning: '#D4820A',
    warningLight: '#FFF4E0',
    success: '#2D8653',
    successLight: '#E8F5F1',
    overlay: 'rgba(26, 107, 90, 0.95)',
  },
  typography: {
    display: { fontSize: 28, fontWeight: '700' as const },
    title: { fontSize: 22, fontWeight: '700' as const },
    sectionHeader: { fontSize: 13, fontWeight: '600' as const, letterSpacing: 0.8, textTransform: 'uppercase' as const },
    bodyPrimary: { fontSize: 16, fontWeight: '400' as const, lineHeight: 25.6 },
    bodySecondary: { fontSize: 14, fontWeight: '400' as const, lineHeight: 21 },
    caption: { fontSize: 12, fontWeight: '400' as const },
    button: { fontSize: 16, fontWeight: '600' as const },
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    xxl: 32,
  },
  radius: {
    pill: 20,
    input: 12,
    card: 16,
    button: 14,
    modal: 24,
  },
  shadow: {
    shadowColor: '#1C2B26',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 3,
  },
};
